### POST request to create a patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Example Name",
  "email": "test9999@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-10-10",
  "registerDate": "2025-11-15"
}

###